version: '3.8'

services:
  database:
    image: mysql:5.7
    container_name: pawang-backend-sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    networks:
      - pawang-networks
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./db_pawang.sql:/docker-entrypoint-initdb.d/db_pawang.sql"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pawang-backend-pma
    depends_on:
      - database
    networks:
      - pawang-networks
    environment:
      - 'PMA_HOST=pawang-backend-sql'
      - 'PMA_PORT=3306'
    ports:
      - 8080:80

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    container_name: pawang-backend-go
    restart: unless-stopped
    networks:
      - pawang-networks

volumes:
  mysql-data:


networks:
  pawang-networks:
