version: '3.8'

services:
  database:
    image: mariadb
    container_name: pawang-backend-sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306"
    networks:
      - pawang-network
    volumes:
      - "mysql-data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pawang-backend-pma
    depends_on:
      - database
    networks:
      - pawang-network
    environment:
      - 'PMA_HOST=pawang-backend-sql'
      - 'PMA_PORT=3306'
    links:
      - database
    ports:
      - 8888:80

  api:
    build: .
    container_name: pawang-backend-api
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "1234:1234"
    volumes:
      - .:/app/pawang-be
    links:
      - database
    networks:
      - pawang-network

volumes:
  mysql-data:


networks:
  pawang-network:
