name: Deploy Pawang Rest API on Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git
      uses: actions/checkout@v3
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker rm -f pawang-backend
          docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker run -d -p 5000:5000 --name pawang-backend ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
