name: Deploy Pawang Rest API on Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git
      uses: actions/checkout@v3
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_PORT: 5000
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        envkey_TOKEN_SECRET_KEY: ${{ secrets.TOKEN_SECRET_KEY }}
        envkey_CONFIG_SMTP_HOST: smtp.gmail.com
        envkey_CONFIG_SENDER_NAME: Pawang <${{ secrets.CONFIG_AUTH_EMAIL }}>
        envkey_CONFIG_AUTH_EMAIL: ${{ secrets.CONFIG_AUTH_EMAIL }}
        envkey_CONFIG_AUTH_PASSWORD: ${{ secrets.CONFIG_AUTH_PASSWORD }}
        envkey_ONESIGNAL_USER_KEY: ${{ secrets.ONESIGNAL_USER_KEY }}
        envkey_ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
        envkey_ONESIGNAL_REST_KEY: ${{ secrets.ONESIGNAL_REST_KEY }}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
        
    - name: Deploy On Azure
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker rm -f pawang-backend
          docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker run -d -p 5000:5000 --restart always -v /home/pawang/pawang-backend/public:/usr/src/app/public --name pawang-backend ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest

    - name: Deploy On Alibaba
      uses: appleboy/ssh-action@master
      with:
        host: "47.250.130.38"
        username: ${{ secrets.SSH_LB_USERNAME }}
        password: ${{ secrets.SSH_LB_PASSWORD }}
        script: |
          docker rm -f pawang-backend
          docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker run -d -p 5000:5000 --restart always -v /root/pawang-backend/public:/usr/src/app/public --name pawang-backend ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest

    - name: Deploy On Recloud
      uses: appleboy/ssh-action@master
      with:
        host: "139.59.99.122"
        username: ${{ secrets.SSH_LB_USERNAME }}
        password: ${{ secrets.SSH_LB_PASSWORD }}
        script: |
          docker rm -f pawang-backend
          docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
          docker run -d -p 5000:5000 --restart always -v /root/pawang-backend/public:/usr/src/app/public --name pawang-backend ${{ secrets.DOCKERHUB_USERNAME }}/pawang-backend:latest
